### ISSUE TITLE
Meta: Move Issues from beedroid-hist to new public repo beedroid

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid#10]
UPDATE: I renamed the beeminder/beedroid-issues repo to beeminder/beedroid so that it can be repurposed as the public Beedroid repo.

(Plan is to copy the current snapshot of the code from the private beeminder/beedroid-hist to the public beeminder/beedroid when it's safe for public consumption.)

The mission for this Issue, if we choose to accept it, is to move all the Issues from beeminder/beedroid-hist to beeminder/beedroid. The Issues already at beeminder/beedroid are old ones from Uluc's reign. He created the public repo beeminder/beedroid-issues which has now been renamed to beeminder/beedroid and is now the stub repo for the public incarnation of the Beedroid repo.

But I don't know if some or all of the Issues should stay with the private repo. Maybe if Issues and commits refer to each other, it will be convenient to keep them there until we're ready to make the transition?

**Comment by adamwolf** [comment]
Done!

I modified some as I migrated them over, mostly obscuring user-submitted reports a bit, and removing user screenshots.
