### ISSUE TITLE
Show onboarding when there are no goals

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid#14]
_From @adamwolf on January 31, 2018 18:33_

Show onboarding text when there are no goals, explaning they need to go to the website and then make it easy for them to do so.

_Copied from original issue: beeminder/beedroid-hist#23_

**Comment by dreeves** [comment]
I liked @adamwolf's suggestion from Feb 7:

> it can say a variety of things, but at a minimum:
> “Hi! Welcome to the Beeminder app! The Beeminder app helps you use Beeminder on the go, but some of Beeminder is only available on the website. It looks like you have no goals set up, so head on over to the website and get started!”

**Comment by adamwolf** [comment]
I looked into this.  There already is onboarding text in that box, but it doesn't seem to be shown when I test it, so I'll dig into that.

**Comment by adamwolf** [comment]
This is now shown!
