### ISSUE TITLE
Did we stop receiving push notifications?

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid#17]
_From @dreeves on January 31, 2018 5:3_

## Probable bug report / thing to investigate

Is Beeminder sending / is Beedroid receiving the push notifications that graph regenerations are done?

Symptom: With Resque queues totally empty, the Infinibee keeps buzzing over the graph in Beedroid for many seconds after the graph has finished regenerating.

This might've been the case for a while and it's been super cockroachy because refresh times are always kind of random. I.e., I may've shamefully been shrugging it off for months and failing to think to report it!

@adamwolf suggests it may have happened around the new year.

_Copied from original issue: beeminder/beedroid-hist#21_

**Comment by dreeves** [comment]
More and more reports of this, I think.

**Comment by adamwolf** [comment]
I suspect this is Google preemptively turning down GCM before the 11th.  It
seems to be getting pretty common for us in the last week.

**Comment by adamwolf** [comment]
I can confirm we are getting push notifications.
