### ISSUE TITLE
layout issue at larger screen size

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid#34]
"Probably not a priority compared to fixing Google SSO, but there appears to be room to improve layout in the Android app on larger screens (screenshot from Pixel).

By the way: SSO still works fine in version 2.2.3 build 9026 that I have until now been using on my Nexus 1 (Gingerbread), so it doesnt look  like it's a change on Google's end that broke it.  But you probably knew that already."

![screenshot_20180211-095644](https://user-images.githubusercontent.com/46881/36324723-42ef3b04-130a-11e8-886f-0716d8bb1717.png)

**Comment by dreeves** [comment]
Your Pixel phone does that? I do not see that on my Pixel2.

**Comment by adamwolf** [comment]
I do not see that on my Pixel 2.  I will look on the simulator on a virtual Pixel 2.

**Comment by adamwolf** [comment]
I do not see this.  I haven't seen it ever, but I've looked at this screen a lot in the last six months.
