### ISSUE TITLE
Widgets should handle goals being archived correctly

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid#4]
Report from user drtall:

Looks like the Android summary widget still doesn't handle goals being archived correctly. The app itself does now, but the widget still shows skull and crossbones for that goal.

Oh and deleting and recreating the widget doesn't fix it.

**Comment by adamwolf** [comment]
Relatedly, the 1x1 widgets don't show any indication that the goal is being archived (per user feedback today).

**Comment by adamwolf** [comment]
See  #80

**Comment by dreeves** [comment]
The bug report here is about actually archived goals? I guess it should show "FIN" instead of crossbones, right? Might be fairly low priority since really the user just wants to either restart the goal or get rid of the widget.

**Comment by adamwolf** [comment]
Right now you have to log out and log back in in order to get an archived goal to stop showing up on your summary widget.

**Comment by adamwolf** [comment]
Reported by multiple users in the past few weeks.

**Comment by krugerk** [comment]
What would the proper behavior be? 
Displaying 'this goal is archived, click here to remove widget' on the widget?

**Comment by adamwolf** [comment]
The primary complaint folks have is not for the single-goal-widget but for
the summary widget.

**Comment by adamwolf** [comment]
A fix for this was added to the release-in-progress.  

For single widgets, It shows a red widget with the username, goalname, and "not found".  When you tap it, it goes to the goal list view. (Apps in android can't delete widgets, unfortunately.) This 'not found' code was already in there, but a bug prevented it from working.
