### ISSUE TITLE
issue with hour/date picker

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid#9]
"In the android app, there's a screen where I can change the times for emergency day notifications (& Zeno polling). In this place, I can change the first time just fine, any of them, but if I want to change a second one, it only opens the "minutes" clock, and altogether glitches. I can't change the hours setting."

 recent android, moto g5

**Comment by adamwolf** [comment]
Reworked the hour/date picker recently, and haven't seen even on moto g5 emulator.
